strategies = [
    "Random Walk Strategy for MSFT stock: Simulate a random walk for asset prices and buy when price increases, sell when price decreases. This strategy assumes no predictive ability, simulating random market movements.",
    "Momentum Strategy: Trade based on the assumption that assets with upward momentum will continue rising and those with downward momentum will continue falling. Can be based on price changes over a time period.",
    "Mean Reversion Strategy: This strategy assumes that prices will revert to their mean. A buy signal is triggered when the price is significantly below the moving average, and a sell signal is triggered when the price is above the moving average.",
    "Buy and Hold Strategy: A simple strategy where an asset is bought at a certain point and held indefinitely. No trades are made unless the strategy is re-evaluated or new rules are applied.",
    "Exponential Moving Average (EMA) Crossover Strategy: This strategy involves two EMAs, one short-term and one long-term. A buy signal occurs when the short-term EMA crosses above the long-term EMA, and a sell signal happens when it crosses below.",
    "Bollinger Bands Strategy: Bollinger Bands consist of a middle moving average and two bands set a certain number of standard deviations above and below the moving average. A buy signal occurs when price hits the lower band, and a sell signal when price hits the upper band.",
    "Adaptive Moving Average (AMA) Strategy: The AMA adjusts to volatility and is more responsive during high volatility periods. A buy signal is generated when the price is above the AMA, and a sell signal when it is below.",
    "Fibonacci Retracement Strategy: This strategy uses key Fibonacci retracement levels (23.6%, 38.2%, 50%, 61.8%) to identify potential reversal points. Buy when price retraces to a lower Fibonacci level and sell when price reaches an upper level.",
    "Price Action Strategy: This strategy relies on reading price patterns and candlestick formations. Buy signals are generated by bullish patterns (e.g., engulfing), and sell signals from bearish patterns (e.g., shooting star).",
    "Keltner Channel Strategy: The Keltner Channel is made of a central EMA with upper and lower bands based on ATR. A buy signal occurs when the price breaks above the upper band, and a sell signal happens when the price breaks below the lower band."
]


def inference(strategy_idea):
  solution = app.invoke({"messages": [("user", strategy_idea)], "iterations": 4, "error": ""})
  prefix = solution["generation"].prefix
  imports = solution["generation"].imports
  code = solution["generation"].code
  print(prefix)
  print(imports)
  print(code)
  return prefix, imports, code

for x in strategies:
  inference(x)


code_to_papertrade = solution["generation"].imports + "\n" + solution["generation"].code
stdout_logs, stderr_logs = paper_trade(code_to_papertrade, True)

if stderr_logs == '':
  # Check if a match is found and extract the content
  match = re.search(r'\{(.*?)\}', stdout_logs)
  if match:
      content = match.group(1)
      print(content)
  else:
      print("No content found")